In [73]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer

### Enter your train words/strings to create vocabulary

In [74]:
string= ["Mary has a little lamb,rain rain go away"]

### Enter your test string for the prediction of the next word

In [75]:
test_string=['mary rain has little little']

#### Building the vocabulary

In [76]:
cv=CountVectorizer()
M1= cv.fit_transform(string)
M1.toarray()

array([[1, 1, 1, 1, 1, 1, 2]], dtype=int64)

In [77]:
v=cv.vocabulary_

Below is the vocabulary- each word has a its own index value 

In [78]:
v2=pd.Series(v)
vocab=v2.sort_values(inplace=False)
vocab

away      0
go        1
has       2
lamb      3
little    4
mary      5
rain      6
dtype: int64

#### No of parameters for the Multinomial model

In [95]:
parameters=vocab.size # give back the number of unique words we have in our vocabulary
parameters

7

#### Processing test_string 

In [92]:
M2= cv.transform(test_string)
M=M2.toarray()
Ni=M2.data # frequency of occurance of each parameters

array([1, 2, 1, 1], dtype=int64)

In [93]:
#Counts of words matching with our Vocabulary
print(M)

[[0 0 1 0 2 1 1]]


In [39]:
#quick glance of the words that have matched
test_result=cv.inverse_transform(M)
test_result

[array(['has', 'little', 'mary', 'rain'], dtype='<U6')]

Calculating Empricial Counts Ni

In [87]:
N=np.sum(M2) #N Total no of events
Ni # frequency of occurance of each parameters

5

#### Setting up the prior and posterior model

In [69]:
prior=1/no_features

Dirichlet Posterior Predictive model= prior+ emprical counts= (α+ Ni)/summation(alpha+N)

In [96]:
p=[]
for i in Ni:
    x=(1+i)/(parameters+N)
    p.append(x)
    

#### Prediction of next word

In [119]:
predictive=pd.Series({'T':test_result,'mode':p})
predictive # gives the words and their probability

T                             [[has, little, mary, rain]]
mode    [0.16666666666666666, 0.25, 0.1666666666666666...
dtype: object

In [121]:
p_max=[max(p)]
p_max # The maximum predictive probability of the word

[0.25]